frontend/src/app/generic-viewer/generic-viewer.page.html
frontend/src/app/list-inscriptions/list-inscriptions.page.html
frontend/src/app/list-tokens/list-tokens.page.html
frontend/src/app/list-tokens/list-tokens.page.ts
frontend/src/app/transfer-modal/transfer-modal.page.ts

This PR implements a few minor tweaks to improve the experience

fix: filter, ordering and other improvements

---

frontend/src/app/list-inscriptions/list-inscriptions.page.html
frontend/src/app/list-inscriptions/list-inscriptions.page.scss
frontend/src/app/view-inscription/view-inscription.page.ts

- Created OG MetaData for Inscriptions
- Fixed the inscription views with text-overflows

Created OG MetaData for Inscriptions

---

frontend/src/app/list-tokens/list-tokens.page.html
frontend/src/app/list-tokens/list-tokens.page.ts
frontend/src/app/markets/markets.page.html
frontend/src/app/markets/markets.page.ts
frontend/src/app/trade-token-v2/trade-token-v2.page.html
frontend/src/app/trade-token-v2/trade-token-v2.page.ts

This PR simplifies and optimises a few areas that pulled a lot of data on load instead of paging lazily

Frontend Optimisations

---

indexer/src/indexer/metaprotocol/marketplace.go

The previous marketplace used the buy transaction timestamp to record the history, the new marketplace should have done the same, but used the listing timestamp instead. 
This means the history was recorded, but not for the date and time the buy was made but rather when the listing was.
This PR fixes that

Fix for trade history timestamps

---

client/.gitignore
client/README.md
client/package-lock.json
client/package.json
client/src/cli.ts
client/src/client.ts
client/src/index.ts
client/src/metaprotocol/inscription.ts
client/src/operations/inscription.ts
client/src/service/asteroid.ts
client/src/zeus/index.patch
client/tsconfig.json

- add `SigningStargateClient#estimate` method
- `AsteroidService#subscription` getter and types for WebSocket operations
- make `InscriptionProtocol#inscribe` metadata and parent generic
- add GraphQL Zeus client generation to `package.json` scripts

@asteroid-protocol/sdk 0.4.0

---

frontend/src/app/markets-inscription/markets-inscription.page.html
frontend/src/app/markets-inscription/markets-inscription.page.scss
frontend/src/app/markets-inscription/markets-inscription.page.ts

This PR improves infinite scrolling and filtering behaviour

Minor tweaks to filters/scrolling

---

frontend/src/app/markets-inscription/markets-inscription.page.scss
frontend/src/app/user-chip/user-chip.component.html
frontend/src/app/user-chip/user-chip.component.ts
frontend/src/app/view-inscription-modal/view-inscription-modal.page.html
frontend/src/app/view-inscription-modal/view-inscription-modal.page.ts

feat: add created by and created date to inscription buy modal

---

client/package-lock.json
client/package.json
client/src/index.ts
client/src/operations/inscription.ts

- feat: export interfaces and functions from tx module

@asteroid-protocol/sdk 0.5.3

---

client/package-lock.json
client/package.json
client/src/zeus/index.patch
client/src/zeus/index.ts

@asteroid-protocol/sdk 0.6.1

---

client/README.md
client/package-lock.json
client/package.json
client/src/crypto.ts
client/src/helpers/zeus.ts
client/src/index.ts

- add client entry point
- remove global usage

@asteroid-protocol/sdk 0.6.2

---

client/asteroid.json
client/package-lock.json
client/package.json
client/src/index.ts
client/src/metaprotocol/cft20.ts
client/src/metaprotocol/inscription.ts
client/src/metaprotocol/marketplace.ts
client/src/metaprotocol/meta.ts
client/src/operations/cft20.ts
client/src/operations/index.ts
client/src/operations/inscription.ts
client/src/operations/marketplace.ts
client/src/operations/meta.ts
client/src/zeus/const.ts
client/src/zeus/index.ts

- graphql schema update
- fix ibc receiver address
- add option to override fee from operations

@asteroid-protocol/sdk 0.6.5

---

client/package-lock.json
client/package.json
client/src/client.ts
client/src/config.ts
client/src/metaprotocol/tx.ts
client/src/simulate-tx-rest.ts

- fee multiplier config option
- add support for ExtensionData to simulate tx with rest endpoint

@asteroid-protocol/sdk 0.6.6

---

client/package-lock.json
client/package.json
client/src/operations/marketplace.ts
client/src/service/asteroid.ts
client/src/zeus/const.ts
client/src/zeus/index.ts

- validate marketplace deposit and buy
- update graphql types

@asteroid-protocol/sdk 0.6.7

---

app/app/components/SubmitTx/Errors.tsx
app/package-lock.json
app/package.json
client/package-lock.json
client/package.json
client/src/simulate-tx-rest.ts

Feat - show estimation error details

---

app/app/routes/app.inscriptions.$clubId._index.tsx
app/app/routes/app.inscriptions._index.tsx

- update rarity sorting in inscription loader
- update latest sales box max width

chore: small ui fixes

---

app/app/components/CollectionDetail.tsx
app/app/components/InscriptionActions.tsx
app/app/components/InscriptionImage.tsx
app/app/components/dialogs/BuyInscriptionDialog.tsx
app/app/hooks/useRoyalty.ts
app/app/routes/app.inscription.$hash.tsx
app/app/routes/app.migrate.inscription.$hash.tsx

- add buy button to inscription detail page
- add collection button to inscription detail page
- inscription buy dialog - make header and action buttons fixed, center part scrollable

feat: inscription detail actions

---

client/README.md
client/example/inscribe-csv/metadata.csv
client/package-lock.json
client/package.json
client/src/cli.ts
client/src/service/asteroid.ts

- inscribe csv - add more info to README
- inscribe csv - support description column in cvs
- inscribe csv - change collection arg to collection symbol

@asteroid-protocol/sdk v0.7.4

---

client/README.md
client/package-lock.json
client/package.json
client/src/cli.ts
client/src/config.ts
client/src/service/asteroid.ts

- add command to list all collection inscriptions
- add useIbc and feeReceiver config options

@asteroid-protocol/sdk v0.7.5

---

client/package-lock.json
client/package.json
client/src/cli.ts

- list inscription - parse price argument as float

@asteroid-protocol/sdk v0.7.6

---

app/app/components/SubmitTx/Errors.tsx
app/app/hooks/useSubmitTx.ts
app/app/routes/app.bridge.($ticker).tsx

- make insufficient funds error message more user friendly
- set bridge amount input value on "your balance" click

feat: bridge improvements 1

---

app/package-lock.json
app/package.json
client/package-lock.json
client/package.json
client/src/config.ts
client/src/constants.ts
client/src/metaprotocol/bridge.ts
client/src/metaprotocol/build.ts
client/src/metaprotocol/cft20.ts
client/src/metaprotocol/inscription.ts
client/src/metaprotocol/launchpad.ts
client/src/metaprotocol/marketplace.ts
client/src/metaprotocol/meta.ts
client/src/metaprotocol/trollbox.ts
client/src/metaprotocol/types.ts
client/src/operations/bridge.ts
trollbox/package-lock.json
trollbox/package.json
uploader/package-lock.json
uploader/package.json
uploader/src/config.ts
uploader/src/scripts/mint-bot.ts

- update indexer fee address
- deploy uploader
- deploy app
- deploy trollbox

feat: default fee
